# Generated by Django 5.2.3 on 2025-07-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
